# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/KV260_GPIO/KV260_GPIO.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO || ORIG_REF_NAME==KV260_GPIO} -quiet] -quiet

# IP: bd/KV260_GPIO/ip/KV260_GPIO_xlslice_0_1/KV260_GPIO_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO_xlslice_0_1 || ORIG_REF_NAME==KV260_GPIO_xlslice_0_1} -quiet] -quiet

# IP: bd/KV260_GPIO/ip/KV260_GPIO_Majority_Module_0_4/KV260_GPIO_Majority_Module_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO_Majority_Module_0_4 || ORIG_REF_NAME==KV260_GPIO_Majority_Module_0_4} -quiet] -quiet

# IP: bd/KV260_GPIO/ip/KV260_GPIO_zynq_ultra_ps_e_0_1/KV260_GPIO_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==KV260_GPIO_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/KV260_GPIO/ip/KV260_GPIO_xlslice_1_0/KV260_GPIO_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO_xlslice_1_0 || ORIG_REF_NAME==KV260_GPIO_xlslice_1_0} -quiet] -quiet

# IP: bd/KV260_GPIO/ip/KV260_GPIO_xlslice_2_0/KV260_GPIO_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO_xlslice_2_0 || ORIG_REF_NAME==KV260_GPIO_xlslice_2_0} -quiet] -quiet

# IP: bd/KV260_GPIO/ip/KV260_GPIO_xlconcat_0_0/KV260_GPIO_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO_xlconcat_0_0 || ORIG_REF_NAME==KV260_GPIO_xlconcat_0_0} -quiet] -quiet

# IP: bd/KV260_GPIO/ip/KV260_GPIO_xlconstant_0_0/KV260_GPIO_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==KV260_GPIO_xlconstant_0_0 || ORIG_REF_NAME==KV260_GPIO_xlconstant_0_0} -quiet] -quiet

# XDC: d:/Projects/Vivado/Majority/Majority.gen/sources_1/bd/KV260_GPIO/ip/KV260_GPIO_zynq_ultra_ps_e_0_1/KV260_GPIO_zynq_ultra_ps_e_0_1_ooc.xdc

# XDC: d:/Projects/Vivado/Majority/Majority.gen/sources_1/bd/KV260_GPIO/ip/KV260_GPIO_zynq_ultra_ps_e_0_1/KV260_GPIO_zynq_ultra_ps_e_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==KV260_GPIO_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==KV260_GPIO_zynq_ultra_ps_e_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Projects/Vivado/Majority/Majority.gen/sources_1/bd/KV260_GPIO/KV260_GPIO_ooc.xdc
